"""
Interactively plot airfoil polar files generated by XFOIL.

The script:
    1. Lets the user select a propeller with generated and smoothened airfoil polars.
    2. Reads all Airfoil_rR*_Re*.txt files from the airfoil_polars folder.
    3. Sorts the available data by blade station r/R and Reynolds number.
    4. Opens an interactive Matplotlib figure with three subplots.
    5. Uses sliders to move through blade stations and Reynolds numbers.
    6. Shows Cl, Cd, and Cm as functions of angle of attack.
    7. Marks the detected positive and negative stall points on the Cl curve.

Reads:
    <propeller>/airfoil_polars/Airfoil_rR*_Re*.txt

Shows:
    - Cl(alpha)
    - Cd(alpha)
    - Cm(alpha)

Use the sliders to move through:
    - blade stations r/R
    - Reynolds numbers
"""

import sys
from pathlib import Path
utilities_dir = Path(__file__).resolve().parent.parent.parent / "src" / "propeller_data"
sys.path.insert(0, str(utilities_dir))
from utilities import *


# =============================================================================
# Input settings
# =============================================================================

# Directory containing the APC <propeller>-PERF.PE0 geometry files
APC_DIRECTORY = (
    Path(__file__).resolve().parent.parent.parent
    / "data"
    / "external"
    / "apc"
    / "geometry"
)

# Directory containing the propeller subfolders
PROP_DIRECTORY = Path(
    Path(__file__).resolve().parent.parent.parent
    / "data"
    / "processed_propellers"
)


# =============================================================================
# Main script
# =============================================================================

def main():
    """
    Run the interactive XFOIL-polar plotting workflow.
    """

    # Ask the user to select a propeller that has generated smoothened airfoil polars
    prop, polar_dir = ask_for_propeller_with_smoothened_polars(
        APC_DIRECTORY,
        PROP_DIRECTORY,
    )

    # Find all generated polar files for the selected propeller
    polar_files = get_polar_files(polar_dir)

    if len(polar_files) == 0:
        raise ValueError(f"No polar files found in {polar_dir.resolve()}")

    # Store all polar data before opening the figure
    # Key format:
    #     (r/R, Reynolds number)
    polar_database = {}

    for path in polar_files:
        rR = extract_rR(path)
        Re = extract_Re(path)

        polar_database[(rR, Re)] = parse_polar_file(path)

    # Create sorted lists of available blade stations and Reynolds numbers
    rR_values = sorted(set(key[0] for key in polar_database.keys()))
    Re_values = sorted(set(key[1] for key in polar_database.keys()))

    # Create figure with three vertically stacked subplots
    fig, axes = plt.subplots(3, 1, figsize=(8, 9), sharex=True)

    # Reserve space below the subplots for the sliders
    plt.subplots_adjust(bottom=0.24, hspace=0.25)

    # Empty line objects are created once and updated by the slider callback
    cl_line, = axes[0].plot([], [], linewidth=1.2)
    cd_line, = axes[1].plot([], [], linewidth=1.2)
    cm_line, = axes[2].plot([], [], linewidth=1.2)

    # Stall markers are shown on the Cl plot only
    stall_points = axes[0].scatter(
        [],
        [],
        color="red",
        s=10,
        zorder=5,
        label="Detected stall",
    )

    axes[0].legend(loc="best")

    axes[0].set_ylabel("$C_l$")
    axes[1].set_ylabel("$C_d$")
    axes[2].set_ylabel("$C_m$")
    axes[2].set_xlabel(r"$\alpha$ [deg]")

    # Use fixed x-limits for all polar plots
    for ax in axes:
        ax.grid(True)
        ax.set_xlim(-90, 90)

    # Fixed limits keep the visual scale constant while moving the sliders
    axes[0].set_ylim(-1.5, 2.5)
    axes[1].set_ylim(-0.5, 2)
    axes[2].set_ylim(-0.4, 0.4)

    # Create blade-station and Reynolds-number sliders
    rR_slider_ax = plt.axes([0.15, 0.105, 0.70, 0.035])
    Re_slider_ax = plt.axes([0.15, 0.045, 0.70, 0.035])

    # The sliders select indices in rR_values and Re_values
    rR_slider = Slider(
        rR_slider_ax,
        "Blade station",
        0,
        len(rR_values) - 1,
        valinit=0,
        valstep=1,
    )

    Re_slider = Slider(
        Re_slider_ax,
        "Re index",
        0,
        len(Re_values) - 1,
        valinit=0,
        valstep=1,
    )

    def update(_):
        """
        Update the polar curves for the selected blade station and Reynolds number.

        The slider values are numbers, but they represent indices in the sorted
        r/R and Reynolds-number lists. Therefore they are converted to integers
        before indexing.
        """

        rR_index = int(rR_slider.val)
        Re_index = int(Re_slider.val)

        rR = rR_values[rR_index]
        Re = Re_values[Re_index]

        key = (rR, Re)

        # Some r/R-Re combinations may be missing
        if key not in polar_database:
            fig.suptitle(
                f"No polar available for r/R = {rR:.3f}, Re = {Re:.3e}",
                fontsize=12,
            )

            cl_line.set_data([], [])
            cd_line.set_data([], [])
            cm_line.set_data([], [])
            stall_points.set_offsets(np.empty((0, 2)))

            fig.canvas.draw_idle()
            return

        polar = polar_database[key]

        alpha = polar["alpha"].to_numpy()
        cl = polar["Cl"].to_numpy()
        cd = polar["Cd"].to_numpy()
        cm = polar["Cm"].to_numpy()

        # Update the aerodynamic coefficient curves
        cl_line.set_data(alpha, cl)
        cd_line.set_data(alpha, cd)
        cm_line.set_data(alpha, cm)

        # Detect the negative and positive stall points
        stall = find_stall_points(alpha, cl, cd, cm)

        stall_alpha = np.array([
            stall["alpha_neg"],
            stall["alpha_pos"],
        ])

        stall_cl = np.array([
            stall["cl_neg"],
            stall["cl_pos"],
        ])

        # Update the plotted stall markers on the Cl curve
        stall_points.set_offsets(
            np.column_stack((stall_alpha, stall_cl))
        )

        fig.suptitle(
            f"APC {prop}: polars at r/R = {rR:.3f} | Re = {int(Re)}",
            fontsize=12,
        )

        fig.canvas.draw_idle()

    # Draw the first selected polar before opening the interactive window
    update(None)

    # Connect the sliders after the initial draw
    rR_slider.on_changed(update)
    Re_slider.on_changed(update)

    plt.show()


if __name__ == "__main__":
    main()